version: "3.8"

name: bobapp
services:
  frontnginx:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./front/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backendapp

  backendapp:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
