name: CI/CD BobApp

on: [push, pull_request]

jobs:
  backend:
    name: test du backend et sonar cloud
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      - name: Java setup
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Installation des dépendences et test
        run: mvn clean install
        working-directory: back
      - name: Récupération du rapport de couverture XML
        uses: actions/upload-artifact@v4
        with:
          name: jacoco
          path: back/target/site/jacoco/jacoco.xml
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Vérifie si le porjet sonar cloud exist, sinon on le créé
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "Token length: ${SONAR_TOKEN}"
          # Vérifiez si le projet existe
          response=$(curl -s -u ${SONAR_TOKEN}: "https://sonarcloud.io/api/projects/search?organization=${{ secrets.SONAR_ORGANIZATION }}&projects=${{ secrets.SONAR_PROJECT_KEY_BACKEND }}" -w "\nHTTP Status: %{http_code}" 2>/dev/null)
          echo "SonarCloud API response: $response"  # Ajoutez cette ligne pour voir la réponse brute

          # Essayez d'extraire la valeur du champ total
          echo "$response"
          total=$(jq '.paging.total' <<< "$response")
          rm response.json

          if [ $? -ne 0 ]; then
              echo "Failed to parse the total from response. Response was: $response"
              exit 1
          fi
          # Affichez la valeur de total pour le débogage
          echo "Total: lala"

          if [ -z "$total" ] || [ "$total" -eq "0" ]; then
            echo "Project does not exist. Creating project..."
            curl -X POST -u ${SONAR_TOKEN}: "https://sonarcloud.io/api/projects/create?organization=${{ secrets.SONAR_ORGANIZATION }}&project=${{ secrets.SONAR_PROJECT_KEY_BACKEND }}&name=${{ secrets.SONAR_PROJECT_NAME }}"
          else
            echo "Project already exists."
          fi
          
      - name: Run SonarQube Analysis
        working-directory: back
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
         mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.host.url=https://sonarcloud.io

  frontend:
    name: test du frontend
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Installation des dépendances
        run: npm install
        working-directory: front
      - name: test angular
        run: npm run test
        working-directory: front
      - name: Récupération du dossier avec les rapports de couvertures
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: front/coverage
