name: CI/CD BobApp

on: [push, pull_request]

jobs:
  backend:
    name: test du backend
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      - name: Java setup
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Installation des dépendences et test
        run: mvn clean install
        working-directory: back
      - name: Récupération du rapport de couverture XML
        uses: actions/upload-artifact@v4
        with:
          name: jacoco
          path: back/target/site/jacoco/jacoco.xml
  frontend:
    name: test du frontend
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Installation des dépendances
        run: npm install
        working-directory: front
      - name: test angular
        run: npm run test
        working-directory: front
      - name: Récupération du dossier avec les rapports de couvertures
        uses: actions/upload-artifact@v4
        with:
          name: istanbul report
          path: front/coverage
