name: CI/CD BobApp

on: [push, pull_request]

jobs:
  backend:
    name: test du backend et sonar cloud
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      - name: Java setup
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Installation des dépendences et test
        run: mvn clean install
        working-directory: back
      - name: Récupération du rapport de couverture XML
        uses: actions/upload-artifact@v4
        with:
          name: jacoco
          path: back/target/site/jacoco/jacoco.xml
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build and analyze
        working-directory: back
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=kilianleybrosop_bobapp
  frontend:
    name: test du frontend
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Installation des dépendances
        run: npm install
        working-directory: front
      - name: test angular
        run: npm run test
        working-directory: front
      - name: Récupération du dossier avec les rapports de couvertures
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: front/coverage
